server:
  port: 8081
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/iot?useSSL=false
    username: root
    password: 123456
  mail:
    host: smtp.qq.com #???????
    username: 417695971@qq.com #QQ??
    password: drvvnzlqxbddcahd #??????
    protocol: smtp #??????
    default-encoding: utf-8
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl